### ISSUE TITLE
macOS: Distorted Input Field When Editing Link Title

### ISSUE THREAD

**Issue by saboorbakshi** [OmChachad/Linkeeper#3]
<img width="1116" alt="macOS_1" src="https://github.com/user-attachments/assets/69b14707-fc9f-4d4d-b821-c085b7a6db4c">

**Comment by OmChachad** [comment]
![Screenshot 2024-09-16 at 2 55 13 PM](https://github.com/user-attachments/assets/5de8a1f7-2d03-4d2e-ad17-145aa975e2b4)

Just re-wrote and improved the animation in the details view. Turns out, this also fixed the distortion issue. Should be OK now in the latest commit.

Thanks for reporting!
